options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - id: "build docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/beamy-bot/beamy-bot:latest",
        ".",
      ]

  - id: "push docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/beamy-bot/beamy-bot:latest",
      ]

  - id: "substitue-env"
    name: "gcr.io/${PROJECT_ID}/envsubst"
    env:
      - "PROJECT_ID=${PROJECT_ID}"
      - "PROJECT_NUMBER=${PROJECT_NUMBER}"
      - "SHORT_SHA=${SHORT_SHA}"
      - "BUILD_ID=${BUILD_ID}"
      - "REGION=asia-southeast1"
    args: ["deployment/**/*.env"]

  - id: "run beamy-bot"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "replace",
        "deployment/cloudrun/service.yaml",
        "--region",
        "asia-southeast1",
        "--project",
        "$PROJECT_ID",
      ]

logsBucket: "gs://${PROJECT_ID}-cloudbuild"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/beamy-bot/beamy-bot:latest"
