steps:
  - id: "build docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/beamy-bot/beamy-bot:latest",
        ".",
      ]

  - id: "push docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/beamy-bot/beamy-bot:latest",
      ]

  - id: "run beamy-bot"
    entrypoint: bash
    args:
      - -c
      - gcloud run services replace ./deployment/cloudrun/service.yaml --region "$REGION" --project "$PROJECT_ID"

images:
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/beamy-bot/beamy-bot:latest"
